In [1]:
import numpy as np

In [2]:
#Definir dos matrices
A=np.array([1,2])
B=np.array([[5,6],[7,8]])

In [3]:
#Calcular la suma de las matrices A y B 
suma_matrices = A + B
#Calcular el producto(el producto elemento por elemento)
producto_matrices= A * B

In [4]:
#Mostrar los resultados
print("matriz A: ")
print(A)
print("\nmatriz B: ")
print(B)


matriz A: 
[1 2]

matriz B: 
[[5 6]
 [7 8]]


In [5]:
print("Suma de las matrices A y B:")
print(suma_matrices)

Suma de las matrices A y B:
[[ 6  8]
 [ 8 10]]


In [6]:
print("Producto de las matrices A y B:")
print(producto_matrices)

Producto de las matrices A y B:
[[ 5 12]
 [ 7 16]]
